server:
  port: 8001
spring:  application:    name: ORDER-SERVICE  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin  jpa:    generate-ddl: false    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true    hibernate:      ddl-auto: create  sql:    init:      mode: always